(() => {
"use strict";
const C=window.NPX_CONFIG||{};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const euro=n=>new Intl.NumberFormat("es-ES",{style:"currency",currency:C.currency||"EUR"}).format(n);
const fmtTime=s=>{s=Math.max(0,Math.floor(s||0));return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")};
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const products={
 empanada:{name:"Empanada de Pollo",price:1.50,icon:"🥟"},
 player:{name:"Multimedia Neon Player X",price:.99,icon:"▶"},
 pack5:{name:"Pack 5 Empanadas",price:7,icon:"🥟"},
 packPlayer3:{name:"Pack 3 Neon Player X",price:2.97,icon:"▶"},
 combo:{name:"Combo Neon",price:15,icon:"⚡"}
};
let cart=store.get("npx_cart",[]), orders=store.get("npx_orders",[]);
let tracks=store.get("npx_tracks",[]), favorites=store.get("npx_favorites",[]), history=store.get("npx_history",[]);
let current=-1, shuffle=false, repeat=false, sleepTimer=null, deferredInstall=null, audioCtx=null, analyser=null, sourceNode=null;
const audio=$("#audioPlayer"),video=$("#videoPlayer"),canvas=$("#visualizer"),ctx=canvas.getContext("2d");

function toast(text){const box=$("#toastContainer"),el=document.createElement("div");el.className="toast";el.textContent=text;box.appendChild(el);requestAnimationFrame(()=>el.classList.add("show"));setTimeout(()=>{el.classList.remove("show");setTimeout(()=>el.remove(),350)},2600)}
function activity(points=1){let n=(store.get("npx_activity",0)||0)+points;store.set("npx_activity",n);let level=Math.min(99,Math.floor(n/10)+1);$("#activityScore").textContent=n;$("#activityLevel").textContent=level;$("#footerActivity").textContent=`NIVEL ${level} · ${n} ACTIVIDAD`}
function stats(){let visits=store.get("npx_visits",0),unique=store.get("npx_unique",0),plays=store.get("npx_plays",0);$("#globalVisits").textContent=visits.toLocaleString("es-ES");$("#globalUniqueVisitors").textContent=unique.toLocaleString("es-ES");$("#globalPlays").textContent=plays.toLocaleString("es-ES")}
function clock(){const d=new Date();$("#clock").textContent=d.toLocaleTimeString("es-ES",{hour12:false});$("#date").textContent=d.toLocaleDateString("es-ES",{day:"2-digit",month:"2-digit",year:"numeric"})}
function nav(id){$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.section===id));$$(".page-section").forEach(s=>s.classList.toggle("active",s.id==="section-"+id));if(id==="store")renderCart();if(id==="orders")renderOrders()}
function setupNav(){$$(".nav-btn,.quick-card").forEach(b=>b.addEventListener("click",()=>nav(b.dataset.section)));$$("[data-scroll-order]").forEach(b=>b.onclick=()=>$("#orderAnchor").scrollIntoView({behavior:"smooth"}))}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
function drawVisualizer(){requestAnimationFrame(drawVisualizer);const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;ctx.clearRect(0,0,w,h);let data;if(analyser){data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(data)}else data=new Uint8Array(96).fill(8);const bars=72,bw=w/bars*.62,gap=w/bars*.38;for(let i=0;i<bars;i++){const v=data[Math.floor(i/bars*data.length)]||6;const bh=Math.max(2,v/255*h*.55);const x=i*w/bars;const g=ctx.createLinearGradient(0,h,0,h-bh);g.addColorStop(0,"#a855f7");g.addColorStop(.6,"#49ff9a");g.addColorStop(1,"#22d3ee");ctx.fillStyle=g;ctx.shadowBlur=10;ctx.shadowColor="#a855f7";ctx.fillRect(x,h-bh,bw,bh)}ctx.shadowBlur=0}
function setupAudioGraph(){if(audioCtx)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=256;sourceNode=audioCtx.createMediaElementSource(audio);sourceNode.connect(analyser);analyser.connect(audioCtx.destination)}
function activeMedia(){return video.src?video:audio}
function stopMedia(){audio.pause();video.pause();audio.removeAttribute("src");video.removeAttribute("src");audio.load();video.load()}
function loadTrack(i,autoplay=true){if(i<0||i>=tracks.length)return;current=i;const t=tracks[i];stopMedia();$("#emptyState").style.display="none";$("#currentTitle").textContent=t.name;$("#currentMeta").textContent=t.type==="video"?"Vídeo local":"Audio local";$("#mediaType").textContent=t.type.toUpperCase();const el=t.type==="video"?video:audio;el.src=t.url;el.volume=+$("#volume").value;el.load();if(t.type==="video")video.style.display="block";else video.style.display="none";$("#favoriteBtn").textContent=favorites.includes(t.id)?"♥":"♡";renderPlaylist();if(autoplay){setupAudioGraph();audioCtx?.resume();el.play().catch(()=>{});playActivity(t)}}
function playActivity(t){let h=history.filter(x=>x.id!==t.id);h.unshift({id:t.id,name:t.name,at:Date.now()});history=h.slice(0,50);store.set("npx_history",history);store.set("npx_plays",(store.get("npx_plays",0)||0)+1);activity(2);stats();renderSpecials()}
function next(){if(!tracks.length)return;let n=shuffle?Math.floor(Math.random()*tracks.length):(current+1)%tracks.length;loadTrack(n,true)}
function togglePlay(){let el=activeMedia();if(!el.src){if(tracks.length)loadTrack(0,true);else toast("Añade un audio o vídeo primero.");return}setupAudioGraph();audioCtx?.resume();el.paused?el.play():el.pause()}
function bindMedia(el){["timeupdate","loadedmetadata"].forEach(ev=>el.addEventListener(ev,()=>{if(el!==activeMedia())return;$("#currentTime").textContent=fmtTime(el.currentTime);$("#duration").textContent=fmtTime(el.duration);$("#progress").value=el.duration?(el.currentTime/el.duration)*100:0}));el.addEventListener("play",()=>{$("#playBtn").textContent="Ⅱ";$("#visualizerStatus").textContent="● PLAYING"});el.addEventListener("pause",()=>{$("#playBtn").textContent="▶";$("#visualizerStatus").textContent="● PAUSED"});el.addEventListener("ended",()=>repeat?loadTrack(current,true):next())}
function addFiles(list){[...list].forEach(file=>{const type=file.type.startsWith("video")?"video":"audio";tracks.push({id:crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random(),name:file.name.replace(/\.[^/.]+$/,""),type,url:URL.createObjectURL(file)});});store.set("npx_tracks",tracks.map(t=>({...t,url:t.url})));renderPlaylist();renderLibrary();activity(tracks.length);toast(`${list.length} archivo(s) añadido(s)`)}
function renderPlaylist(){const q=$("#playlistSearch").value.toLowerCase(),cat=$(".category-btn.active")?.dataset.category||"all";let list=tracks.filter(t=>(!q||t.name.toLowerCase().includes(q))&&(cat==="all"||(cat==="favorites"&&favorites.includes(t.id))||t.type===cat));$("#trackCount").textContent=list.length;$("#playlist").innerHTML=list.length?list.map(t=>`<button class="track ${tracks[current]?.id===t.id?"active":""}" data-track="${t.id}"><span class="track-icon">${t.type==="video"?"🎬":"🎵"}</span><span><b>${esc(t.name)}</b><small>${t.type==="video"?"Vídeo":"Audio"}</small></span><i>${favorites.includes(t.id)?"♥":"♡"}</i></button>`).join(""):`<div class="empty-list">No hay archivos aquí.<br><small>Usa «📁 Añadir» para cargar música o vídeo.</small></div>`;$$("[data-track]").forEach(b=>b.onclick=()=>loadTrack(tracks.findIndex(t=>t.id===b.dataset.track),true))}
function renderLibrary(){const q=$("#librarySearch").value.toLowerCase();let list=tracks.filter(t=>t.name.toLowerCase().includes(q));$("#libraryCount").textContent=list.length;$("#myMusicList").innerHTML=list.length?list.map(t=>`<button class="music-item" data-track="${t.id}"><span>${t.type==="video"?"🎬":"🎵"}</span><div><b>${esc(t.name)}</b><small>${t.type}</small></div><strong>▶</strong></button>`).join(""):`<div class="empty-list">Tu biblioteca está preparada para tus archivos locales.</div>`;$$(".music-item").forEach(b=>b.onclick=()=>loadTrack(tracks.findIndex(t=>t.id===b.dataset.track),true))}
function renderSpecials(){let fav=tracks.filter(t=>favorites.includes(t.id));$("#favoriteCount").textContent=`${fav.length} canciones`;$("#favoriteSectionCount").textContent=fav.length;$("#favoritesList").innerHTML=fav.length?fav.map(t=>special(t)).join(""):`<div class="empty-list">Aún no tienes favoritos.</div>`;$("#historyCount").textContent=`${history.length} reproducciones`;let hm=history.map(h=>tracks.find(t=>t.id===h.id)||h);$("#historyList").innerHTML=hm.length?hm.map(t=>special(t)).join(""):`<div class="empty-list">Tu historial aparecerá al reproducir.</div>`;$$(".special-item").forEach(b=>b.onclick=()=>{let i=tracks.findIndex(t=>t.id===b.dataset.track);if(i>=0)loadTrack(i,true)})}
function special(t){return `<button class="special-item" data-track="${t.id}"><span>${t.type==="video"?"🎬":"🎵"}</span><div><b>${esc(t.name)}</b><small>${t.type}</small></div><strong>▶</strong></button>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function cartSub(){return cart.reduce((s,i)=>s+products[i.id].price*i.qty,0)}
function cartShip(){return document.querySelector('input[name="delivery"]:checked')?.value==="home"&&cart.length?(C.deliveryFee||0):0}
function cartTotal(){return cartSub()+cartShip()}
function addCart(id,qty=1){const x=cart.find(i=>i.id===id);x?x.qty+=qty:cart.push({id,qty});store.set("npx_cart",cart);renderCart();activity(1);toast(`${products[id].name} añadido al carrito`)}
function removeCart(id){cart=cart.filter(i=>i.id!==id);store.set("npx_cart",cart);renderCart()}
function renderCart(){const list=$("#summaryItems");$("#navCart").textContent=cart.reduce((s,i)=>s+i.qty,0);if(!cart.length){list.innerHTML='<div class="empty-list">🛒 Carrito vacío.<br><small>Elige un producto para comenzar.</small></div>'}else list.innerHTML=cart.map(i=>`<div class="summary-item"><div><b>${products[i.id].icon} ${esc(products[i.id].name)}</b><small>${i.qty} × ${euro(products[i.id].price)}</small><div class="mini-qty"><button data-cminus="${i.id}">−</button><span>${i.qty}</span><button data-cplus="${i.id}">+</button></div></div><strong>${euro(products[i.id].price*i.qty)}</strong><button class="remove-line" data-cremove="${i.id}">×</button></div>`).join("");$("#subtotal").textContent=euro(cartSub());$("#shipping").textContent=cartShip()?euro(cartShip()):"GRATIS";$("#grandTotal").textContent=euro(cartTotal());$$("[data-cplus]").forEach(b=>b.onclick=()=>addCart(b.dataset.cplus));$$("[data-cminus]").forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.cminus);if(x.qty>1)x.qty--;else removeCart(b.dataset.cminus);store.set("npx_cart",cart);renderCart()});$$("[data-cremove]").forEach(b=>b.onclick=()=>removeCart(b.dataset.cremove))}
function orderData(){const f=$("#orderForm");return{name:f.name.value.trim(),phone:f.phone.value.trim(),delivery:f.delivery.value,address:f.address.value.trim(),date:f.date.value,time:f.time.value,notes:f.notes.value.trim(),payment:f.payment.value}}
function orderText(d){const lines=cart.map(i=>`🥟 *${products[i.id].name}:* ${i.qty} × ${euro(products[i.id].price)}`).join("\n");const delivery=d.delivery==="home"?`🏠 *Entrega:* Domicilio\n📍 *Dirección:* ${d.address}\n🚚 *Gasto de envío:* ${euro(C.deliveryFee||0)}`:`🚉 *Entrega:* Recogida GRATIS\n📍 *Punto:* ${C.pickupPoint}`;return `⚡ *NEON PLAYER X — NUEVO PEDIDO*\n\n👤 *Nombre:* ${d.name}\n📱 *Teléfono:* ${d.phone}\n\n${lines}\n\n💶 *Subtotal:* ${euro(cartSub())}\n${delivery}\n💳 *Pago:* ${d.payment==="paypal"?"PayPal":d.payment==="cash"?"Metálico":"Confirmación por WhatsApp"}\n💰 *Total:* ${euro(cartTotal())}\n📅 *Fecha:* ${d.date}\n⏰ *Hora:* ${d.time}\n📝 *Notas:* ${d.notes||"Sin notas"}`}
function validate(d){if(!cart.length){toast("El carrito está vacío.");return false}if(!d.name||!d.phone||!d.date||!d.time){toast("Completa los campos obligatorios.");return false}if(d.delivery==="home"&&!d.address){toast("Introduce la dirección de entrega.");return false}return true}
function sendWhatsApp(d,paid=false){let text=orderText(d)+(paid?"\n\n✅ *Pago PayPal completado.*":"");window.open(`https://wa.me/${C.whatsapp}?text=${encodeURIComponent(text)}`,"_blank");saveOrder(d,paid?"Pagado PayPal":"Pendiente");}
function saveOrder(d,status){orders.unshift({id:"NPX-"+Date.now().toString().slice(-8),created:Date.now(),status,total:cartTotal(),data:d,items:cart.map(i=>({...i}))});orders=orders.slice(0,30);store.set("npx_orders",orders);store.set("npx_activity",(store.get("npx_activity",0)||0)+5);$("#activityScore").textContent=store.get("npx_activity",0);renderOrders()}
function renderOrders(){const el=$("#ordersList");if(!orders.length){el.innerHTML='<div class="empty-list">Todavía no hay pedidos guardados en este dispositivo.</div>';return}el.innerHTML=orders.map(o=>`<article class="order-item"><header><b>${o.id}</b><span>${new Date(o.created).toLocaleString("es-ES")}</span></header><div>${o.items.map(i=>`${products[i.id].name} × ${i.qty}`).join(" · ")}</div><footer><span>${o.data.delivery==="home"?"🏠 Domicilio":"🚉 Recogida"}</span><strong>${euro(o.total)}</strong><em>${o.status}</em></footer></article>`).join("")}
let paypalRendered=false;
function loadPayPal(){if(paypalRendered||!C.paypalClientId)return;const s=document.createElement("script");s.src=`https://www.paypal.com/sdk/js?client-id=${encodeURIComponent(C.paypalClientId)}&currency=EUR&intent=capture`;s.onload=()=>renderPayPal();document.head.appendChild(s)}
function renderPayPal(){if(!window.paypal||paypalRendered)return;paypalRendered=true;window.paypal.Buttons({style:{layout:"vertical",shape:"rect",label:"paypal",height:45},createOrder:(data,actions)=>actions.order.create({purchase_units:[{description:"Pedido NEON PLAYER X",amount:{currency_code:"EUR",value:cartTotal().toFixed(2)}}]}),onApprove:(data,actions)=>actions.order.capture().then(()=>{const d=orderData();if(validate(d)){sendWhatsApp(d,true);toast("Pago PayPal realizado correctamente.");}}),onError:()=>toast("PayPal no ha podido procesar el pago.")}).render("#paypal-button-container")}
function updatePayment(){const p=document.querySelector('input[name="payment"]:checked')?.value;$("#paypalBox").classList.toggle("hidden",p!=="paypal");if(p==="paypal")loadPayPal()}
function radioIcon(kind){
const icons={music:'♪',sports:'⚡',news:'◌'}; return icons[kind]||'◉';
}
function radioList(){
const stations=[
{name:"LOS40",code:"40",genre:"Éxitos · Pop · España",category:"music",url:"https://play.los40.com/",stream:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40AAC.aac",accent:"#ff315d"},
{name:"LOS40 Classic",code:"40C",genre:"Clásicos · 70s/80s/90s",category:"music",url:"https://play.los40.com/emisora/los40_classic/",stream:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_CLASSICAAC.aac",accent:"#b66cff"},
{name:"LOS40 Dance",code:"40D",genre:"Dance · Electronic · DJs",category:"music",url:"https://play.los40.com/emisora/los40_dance",stream:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_DANCEAAC.aac",accent:"#5dff9a"},
{name:"LOS40 Urban",code:"40U",genre:"Urban · Hip Hop · Reggaetón",category:"music",url:"https://play.los40.com/emisora/los40_urban",stream:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_URBANAAC.aac",accent:"#6d8cff"},
{name:"Europa FM",code:"EF",genre:"Pop · Éxitos · Entretenimiento",category:"music",url:"https://www.europafm.com/directo/",stream:"https://radio-atres-live.ondacero.es/api/livestream-redirect/EFMAAC.aac",accent:"#ff9d45"},
{name:"KISS FM España",code:"KISS",genre:"80s · 90s · Éxitos",category:"music",url:"https://www.kissfm.es/directo/",stream:"https://kissfm.kissfmradio.cires21.com/kissfm.mp3",accent:"#ff4f9a"},
{name:"Radiolé",code:"RL",genre:"Música española · Flamenco · Popular",category:"music",url:"https://play.radiole.com",stream:"https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOLE.mp3",accent:"#ffd45a"},
{name:"Rock FM",code:"RF",genre:"Rock clásico · España",category:"music",url:"https://www.rockfm.fm/",stream:"https://rockfm-cope.flumotion.com/playlist.m3u8",accent:"#d7d7e4"},
{name:"Radio MARCA",code:"RM",genre:"Fútbol · Deportes · Marcador",category:"sports",url:"https://www.marca.com/radio.html",stream:"https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOMARCA_NACIONAL.mp3",accent:"#ff315d"},
{name:"Deportes COPE",code:"COPE",genre:"Fútbol · Tiempo de Juego · Deportes",category:"sports",url:"https://www.cope.es/directos",stream:"https://flucast09-h-cloud.flumotion.com/cope/net1.mp3",accent:"#ffe36b"},
{name:"RAC1",code:"R1",genre:"Deportes · Actualidad · Cataluña",category:"sports",url:"https://www.rac1.cat/directe",stream:"https://playerservices.streamtheworld.com/api/livestream-redirect/RAC_1.mp3",accent:"#ff4a4a"},
{name:"RNE Radio Nacional",code:"RNE",genre:"Noticias · Actualidad · España",category:"news",url:"https://www.rtve.es/play/radio/rne/",stream:"https://rtvelivestream.rtve.es/rtvesec/rne/rne_r1_main.m3u8",accent:"#54e8ff"}
];
const list=$("#radioList");
list.innerHTML=stations.map((r,i)=>`<article class="radio-item" data-radio="${i}" data-category="${r.category}" style="--station-accent:${r.accent}"><span class="radio-station-icon station-logo" aria-hidden="true"><span class="station-logo-core"><b>${esc(r.code||r.name.slice(0,3).toUpperCase())}</b><i></i></span></span><div class="radio-item-main"><b>${r.name}</b><small>${r.genre}</small><em>${r.category==="sports"?"DIRECTO DEPORTIVO":r.category==="news"?"ACTUALIDAD":"MÚSICA"}</em></div><div class="radio-item-actions"><button type="button" class="radio-select"><span>${iconSVG("▶")}</span> ESCUCHAR</button><a href="${r.url}" target="_blank" rel="noopener">WEB ↗</a></div></article>`).join("");
return stations;
}
function setupRadio(){
const stations=radioList();
const player=document.createElement('audio'); player.id='radioAudio'; player.preload='none'; player.crossOrigin='anonymous'; player.volume=1; document.body.appendChild(player);
let idx=-1, switching=false, fadeTimer=null;
const stage=$("#radioStage"), embedWrap=$("#radioEmbedWrap"), embed=$("#radioEmbed");
if(embed) embed.style.display='none';
if(embedWrap){embedWrap.innerHTML='<div class="radio-native-player"><div class="radio-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><strong id="radioNativeTitle">Selecciona una emisora</strong><span id="radioNativeMeta">Reproducción directa integrada en NEON PLAYER X</span><div class="radio-native-progress"><span></span></div></div>'}
const nativeTitle=$("#radioNativeTitle"), nativeMeta=$("#radioNativeMeta"), progress=$(".radio-native-progress span");
function fadeTo(target,duration=260,done){clearInterval(fadeTimer);const from=player.volume,steps=12,delta=(target-from)/steps;let n=0;fadeTimer=setInterval(()=>{n++;player.volume=Math.max(0,Math.min(1,from+delta*n));if(n>=steps){clearInterval(fadeTimer);player.volume=target;done&&done()}},duration/steps)}
function markActive(){ $$(".radio-item").forEach((el,i)=>el.classList.toggle('active',i===idx)); }
async function selectStation(i){
const r=stations[+i]; if(!r)return; idx=+i; switching=true; markActive(); stage.classList.add("switching","loading"); stage.classList.remove("stream-error");
$("#radioName").textContent=r.name; $("#radioGenre").textContent=r.genre; $("#radioIcon").innerHTML=`<span class="stage-station-logo">${esc(r.code||"RADIO")}</span>`; $("#radioOfficial").href=r.url; $("#radioStatus").textContent="● CONECTANDO"; $("#radioStatus").classList.add("on");
if(nativeTitle)nativeTitle.textContent=r.name; if(nativeMeta)nativeMeta.textContent=r.genre+" · directo integrado";
if(embed) { embed.classList.remove("ready"); embed.src="about:blank"; }
fadeTo(0,220,()=>{
  player.pause(); player.removeAttribute("src"); player.load(); player.src=r.stream; player.load(); player.volume=+$("#radioVolume").value;
  const start=()=>{ player.play().then(()=>{ switching=false; stage.classList.remove("switching","loading"); $("#radioStatus").textContent="● EN DIRECTO"; toast(r.name+" · en directo"); activity(1); }).catch(()=>fallbackOfficial(r)); };
  player.addEventListener("canplay",start,{once:true});
  player.addEventListener("error",()=>fallbackOfficial(r),{once:true});
  setTimeout(()=>{if(switching)start()},3200);
});
function fallbackOfficial(st){
  if(!switching)return;
  switching=false; stage.classList.remove("switching","loading"); stage.classList.add("stream-error"); $("#radioStatus").textContent="● DIRECTO OFICIAL";
  if(embed && /^https:\/\//.test(st.url)){ embed.src=st.url; embed.classList.add("ready"); embed.style.display="block"; embedWrap.classList.add("official-fallback"); }
  toast(st.name+" · usando reproductor oficial integrado");
}
}
$$("[data-radio]").forEach(b=>b.querySelector('.radio-select').onclick=()=>selectStation(b.dataset.radio));
$("#radioPlay").onclick=()=>{if(idx<0)selectStation(0);else if(player.paused)player.play().catch(()=>selectStation(idx));else player.pause()};
$("#radioVolume").oninput=e=>{player.volume=+e.target.value;$("#radioVolumeValue").textContent=Math.round(player.volume*100)+'%'};
player.addEventListener('play',()=>{$("#radioPlay").textContent='❚❚';$("#radioStatus").textContent='● EN DIRECTO'});
player.addEventListener('pause',()=>{$("#radioPlay").textContent='▶'});
player.addEventListener('error',()=>{$("#radioStatus").textContent='● STREAM NO DISPONIBLE';stage.classList.add('stream-error')});
player.addEventListener('playing',()=>stage.classList.remove('stream-error'));
$$('[data-radio-filter]').forEach(b=>b.onclick=()=>{$$('[data-radio-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.radioFilter;$$("#radioList .radio-item").forEach(x=>x.style.display=(f==='all'||x.dataset.category===f)?'grid':'none')});
$("#radioSearch").oninput=e=>{const q=e.target.value.toLowerCase();$$("#radioList .radio-item").forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'grid':'none')};
}
function iconSVG(key){const p={'▶': '<path d="M7 5.8v12.4a1.8 1.8 0 0 0 2.8 1.5l9.2-6.2a1.8 1.8 0 0 0 0-3L9.8 4.3A1.8 1.8 0 0 0 7 5.8Z"/>', '♫': '<path d="M9 18V6l10-2v12"/><circle cx="6.5" cy="18" r="2.5"/><circle cx="16.5" cy="16" r="2.5"/>', '♥': '<path d="M20.8 8.8c0 5.3-8.8 10.2-8.8 10.2S3.2 14.1 3.2 8.8A4.7 4.7 0 0 1 12 6.3a4.7 4.7 0 0 1 8.8 2.5Z"/>', '◷': '<circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/>', '◉': '<circle cx="12" cy="12" r="8.5"/><circle cx="12" cy="12" r="3"/>', '▣': '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/>', '□': '<rect x="5" y="4" width="14" height="16" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/>', '🔀': '<path d="M4 7h3c4 0 5 10 10 10h3"/><path d="m17 14 3 3-3 3M4 17h3c1.5 0 2.5-1 3.2-2"/><path d="m17 4 3 3-3 3"/><path d="M4 7h3c1.4 0 2.4.8 3.2 2"/>', '⏪': '<path d="m11 7-6 5 6 5V7Zm8 0-6 5 6 5V7Z"/>', '⏩': '<path d="m5 7 6 5-6 5V7Zm8 0 6 5-6 5V7Z"/>', '🔁': '<path d="M7 7h10l-2-2m2 2-2 2M17 17H7l2 2m-2-2 2-2"/>', '🔊': '<path d="M4 10v4h4l5 4V6l-5 4H4Z"/><path d="M16 9c1.5 1.2 1.5 4.8 0 6M18.5 7c3 2.5 3 7.5 0 10"/>', '🔇': '<path d="M4 10v4h4l5 4V6l-5 4H4Z"/><path d="m17 9 4 6m0-6-4 6"/>', '🛒': '<circle cx="9" cy="19" r="1.5"/><circle cx="18" cy="19" r="1.5"/><path d="M3 4h2l2 10h11l2-7H6"/>', '📻': '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="2"/><path d="M12 4V2M5.5 6.5 4 5M18.5 6.5 20 5"/>', '🎧': '<path d="M4 13a8 8 0 0 1 16 0v5a2 2 0 0 1-2 2h-2v-7h4M4 13v5a2 2 0 0 0 2 2h2v-7H4"/>', '🕘': '<circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/>', '🛍': '<path d="M5 8h14l-1 11H6L5 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/>'}[key]||'';return p?`<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">${p}</svg>`:''}
function upgradeIcons(){
const replacements=[...document.querySelectorAll('.nav-icon,.quick-card strong,.control-btn,.play-btn,.small-btn,.icon-btn,.category-btn,.clear-btn')];
replacements.forEach(el=>{const raw=(el.textContent||'').trim();const key=Object.keys({'▶':1,'♫':1,'♥':1,'◷':1,'◉':1,'▣':1,'□':1,'🔀':1,'⏪':1,'⏩':1,'🔁':1,'🔊':1,'🔇':1,'🛒':1,'📻':1,'🎧':1,'🕘':1,'🛍':1}).find(k=>raw.includes(k));if(key){el.innerHTML=iconSVG(key)+(raw.replace(key,'').trim()?`<span>${raw.replace(key,'').trim()}</span>`:'');el.classList.add('icon-upgraded')}});
}
function init(){upgradeIcons();const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();clock();setInterval(clock,1000);resizeCanvas();drawVisualizer();window.addEventListener("resize",resizeCanvas);setupNav();bindMedia(audio);bindMedia(video);renderPlaylist();renderLibrary();renderSpecials();renderCart();renderOrders();setupRadio();
if(!sessionStorage.getItem("npx_visit")){sessionStorage.setItem("npx_visit","1");store.set("npx_visits",(store.get("npx_visits",0)||0)+1);store.set("npx_unique",(store.get("npx_unique",0)||0)+1)}stats();activity(0);
$("#fileInput").onchange=e=>addFiles(e.target.files);
$("#playBtn").onclick=togglePlay;$("#backBtn").onclick=()=>{const e=activeMedia();e.currentTime=Math.max(0,e.currentTime-10)};$("#forwardBtn").onclick=()=>{const e=activeMedia();e.currentTime=Math.min(e.duration||0,e.currentTime+10)};$("#progress").oninput=e=>{const el=activeMedia();if(el.duration)el.currentTime=(+e.target.value/100)*el.duration};$("#volume").oninput=e=>{audio.volume=video.volume=+e.target.value;$("#volumeValue").textContent=Math.round(+e.target.value*100)+"%"};$("#muteBtn").onclick=()=>{const muted=!activeMedia().muted;audio.muted=video.muted=muted;$("#muteBtn").textContent=muted?"🔇":"🔊"};$("#shuffleBtn").onclick=()=>{shuffle=!shuffle;$("#shuffleStatus").textContent="ALEATORIO "+(shuffle?"ON":"OFF")};$("#repeatBtn").onclick=()=>{repeat=!repeat;$("#repeatStatus").textContent="REPETIR "+(repeat?"ON":"OFF")};$("#favoriteBtn").onclick=()=>{if(current<0)return;const id=tracks[current].id;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];store.set("npx_favorites",favorites);$("#favoriteBtn").textContent=favorites.includes(id)?"♥":"♡";renderPlaylist();renderSpecials()};$("#fullscreenBtn").onclick=()=>$("#visualizerContainer").requestFullscreen?.();
$("#playlistSearch").oninput=renderPlaylist;$("#librarySearch").oninput=renderLibrary;$$(".category-btn").forEach(b=>b.onclick=()=>{$$(".category-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPlaylist()});$("#clearPlaylist").onclick=()=>{tracks=[];store.set("npx_tracks",[]);current=-1;stopMedia();$("#emptyState").style.display="grid";renderPlaylist();renderLibrary();renderSpecials()};
$("#clearHistory").onclick=()=>{history=[];store.set("npx_history",[]);renderSpecials()};$("#themeBtn").onclick=()=>{const themes=["purple","blue","matrix","synthwave"],cur=document.body.dataset.theme||"purple";document.body.dataset.theme=themes[(themes.indexOf(cur)+1)%themes.length];store.set("npx_theme",document.body.dataset.theme)};document.body.dataset.theme=store.get("npx_theme","purple");
$("#sleepBtn").onclick=()=>$("#sleepPanel").classList.toggle("open");$$(".sleep-panel button").forEach(b=>b.onclick=()=>{clearTimeout(sleepTimer);let m=+b.dataset.minutes;if(!m){$("#sleepStatus").textContent="Temporizador apagado";return}$("#sleepStatus").textContent=`Se detendrá en ${m} min`;sleepTimer=setTimeout(()=>{activeMedia().pause();$("#sleepStatus").textContent="Temporizador completado"},m*60000)});
$$("[data-add]").forEach(b=>b.onclick=()=>addCart(b.dataset.add));$$("[data-shop-plus]").forEach(b=>b.onclick=()=>{let e=$(`#shopQty-${b.dataset.shopPlus}`);e.textContent=+e.textContent+1});$$("[data-shop-minus]").forEach(b=>b.onclick=()=>{let e=$(`#shopQty-${b.dataset.shopMinus}`);e.textContent=Math.max(1,+e.textContent-1)});$$("[data-add]").forEach(b=>{if(b.closest(".shop-card"))b.onclick=()=>addCart(b.dataset.add,+$(`#shopQty-${b.dataset.add}`).textContent)});
$("#clearCart").onclick=()=>{cart=[];store.set("npx_cart",cart);renderCart()};$$('input[name="delivery"]').forEach(x=>x.onchange=()=>{$("#addressWrap").style.display=x.checked&&x.value==="home"?"block":"none";renderCart()});$$('input[name="payment"]').forEach(x=>x.onchange=updatePayment);$("#orderDate").min=new Date().toISOString().slice(0,10);$("#orderDate").value=$("#orderDate").min;
$("#orderForm").onsubmit=e=>{e.preventDefault();const d=orderData();if(!validate(d))return;if(d.payment==="paypal"){updatePayment();toast("Usa el botón PayPal para completar el pago.");$("#paypalBox").scrollIntoView({behavior:"smooth",block:"center"})}else sendWhatsApp(d)};$("#whatsappOrder").onclick=()=>{const d=orderData();if(validate(d))sendWhatsApp(d)};
$("#clearOrders").onclick=()=>{orders=[];store.set("npx_orders",orders);renderOrders()};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("#installBtn").hidden=true;activity(10);store.set("npx_installs",(store.get("npx_installs",0)||0)+1)};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});window.addEventListener("appinstalled",()=>{activity(10);toast("NEON PLAYER X instalado")})
}
document.addEventListener("DOMContentLoaded",init);
})();