const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const CONFIG={whatsapp:"34602487576",shipping:3,paypalClientId:"BAAE-_0bpY5bp5POKN2LqiDTn-tTh6E7JiCQ_pAPSeU4hOum0sHF1sMJzQ0APl7YKnxk-QTxE_2VN90Dy4"};
const PRODUCTS={
 empanada:{name:"Empanada de Pollo",price:1.50,icon:"🥟"},
 player:{name:"Multimedia Neon Player X",price:.99,icon:"▶"},
 pack5:{name:"Pack 5 Empanadas",price:7,icon:"🥟"},
 pack3:{name:"Pack 3 Neon Player X",price:2.97,icon:"▶"},
 combo:{name:"Combo Neon",price:15,icon:"⚡"}
};
const euro=n=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(n);
let cart=JSON.parse(localStorage.getItem("neonCart")||"[]");
let playlist=[],currentIndex=-1,currentMedia=null,shuffle=false,repeat="off",sleepTimer=null;
let favorites=JSON.parse(localStorage.getItem("neonFavorites")||"[]");
let history=JSON.parse(localStorage.getItem("neonHistory")||"[]");
let themeIndex=+(localStorage.getItem("neonThemeIndex")||0);
const themes=["purple","blue","synthwave","matrix"];
const radios=[
{name:"LOS40 España",country:"España",genre:"Pop / Éxitos",tags:["Pop"],icon:"🇪🇸",url:"https://playerservices.streamtheworld.com/api/livestream-redirect/Los40.mp3",web:"https://los40.com/"},
{name:"LOS40 Classic",country:"España",genre:"Clásicos",tags:["Clásica"],icon:"🎸",url:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_CLASSIC.mp3",web:"https://los40.com/"},
{name:"LOS40 Urban",country:"España",genre:"Urbano / Reguetón",tags:["Urbano"],icon:"🔥",url:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_URBAN.mp3",web:"https://los40.com/"},
{name:"LOS40 Dance",country:"Europa",genre:"Dance / Electrónica",tags:["Urbano"],icon:"💿",url:"https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40_DANCE.mp3",web:"https://los40.com/"},
{name:"KISS FM",country:"España",genre:"80s / 90s / Pop",tags:["Pop"],icon:"💜",url:"https://kissfm.kissfmradio.cires21.com/kissfm.mp3",web:"https://www.kissfm.es/"},
{name:"Radio Nacional",country:"España",genre:"Actualidad / Música",tags:["Pop"],icon:"🇪🇸",url:"https://dispatcher.rndfnk.com/crtve/rne1/main/mp3/high",web:"https://www.rtve.es/play/radio/rne/"},
{name:"Radio 3",country:"España",genre:"Música alternativa",tags:["Pop","Urbano"],icon:"🎧",url:"https://radio3.rtveradio.cires21.com/radio3_hc.mp3",web:"https://www.rtve.es/play/radio/radio-3/"},
{name:"Radio Clásica",country:"España",genre:"Música clásica",tags:["Clásica"],icon:"🎻",url:"https://radioclasica.rtveradio.cires21.com/radioclasica_hc.mp3",web:"https://www.rtve.es/play/radio/"}
];
function save(){localStorage.setItem("neonCart",JSON.stringify(cart));localStorage.setItem("neonFavorites",JSON.stringify(favorites));localStorage.setItem("neonHistory",JSON.stringify(history.slice(0,50)))}
function toast(msg){const d=document.createElement("div");d.className="toast";d.textContent=msg;$("#toastContainer").appendChild(d);setTimeout(()=>d.remove(),2600)}
function updateClock(){const d=new Date();$("#liveDate").textContent=d.toLocaleDateString("es-ES");$("#liveTime").textContent=d.toLocaleTimeString("es-ES",{hour12:false})}
function activity(){const s=JSON.parse(localStorage.getItem("neonStats")||'{"visits":0,"plays":0,"installs":0,"shares":0,"orders":0}');const score=s.visits+s.plays+s.installs+s.shares;const level=score>=1000?10:score>=500?9:score>=250?8:score>=150?7:score>=100?6:score>=60?5:score>=30?4:score>=15?3:score>=5?2:1;$("#activityLevel").textContent=`NIVEL ${level}`;$("#activityScore").textContent=score;$("#footerActivity").textContent=`NIVEL ${level} · ${score} ACTIVIDAD`;document.body.dataset.activityLevel=level}
function stat(k){const s=JSON.parse(localStorage.getItem("neonStats")||'{"visits":0,"plays":0,"installs":0,"shares":0,"orders":0}');s[k]=(s[k]||0)+1;localStorage.setItem("neonStats",JSON.stringify(s));activity()}
function openSection(name){$$(".page-section").forEach(x=>x.classList.remove("active"));$$(".nav-btn").forEach(x=>x.classList.remove("active"));const sec=$(`#section-${name}`);if(sec)sec.classList.add("active");const btn=document.querySelector(`.nav-btn[data-section="${name}"]`);if(btn)btn.classList.add("active");if(name==="favorites")renderFavorites();if(name==="history")renderHistory();window.scrollTo({top:0,behavior:"smooth"})}
$$("[data-section]").forEach(b=>b.addEventListener("click",()=>openSection(b.dataset.section)));
function formatTime(s){if(!Number.isFinite(s))return"00:00";s=Math.max(0,Math.floor(s));return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
const audio=$("#audioPlayer"),video=$("#videoPlayer"),canvas=$("#visualizer"),ctx=canvas.getContext("2d");
function resizeCanvas(){canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio}
addEventListener("resize",resizeCanvas);resizeCanvas();
function drawVisualizer(){ctx.clearRect(0,0,canvas.width,canvas.height);const w=canvas.width,h=canvas.height,t=Date.now()/900;for(let i=0;i<44;i++){const x=w/2+(Math.sin(i*.45+t)*.42*w),bar=(Math.sin(t*2+i*.55)+1)*.12*h+18;ctx.fillStyle=i%3===0?"#49ff9a":"#a855f7";ctx.globalAlpha=.25;ctx.fillRect(x,h/2-bar/2,3,bar)}ctx.globalAlpha=1;requestAnimationFrame(drawVisualizer)}drawVisualizer();
function activeEl(){return currentMedia==="video"?video:audio}
function stopPlayers(){audio.pause();video.pause();video.classList.remove("video-active");audio.removeAttribute("src");video.removeAttribute("src");$("#emptyState").classList.remove("hidden");$("#fullscreenBtn").classList.remove("visible")}
function loadTrack(i,auto=true){if(i<0||i>=playlist.length)return;currentIndex=i;const t=playlist[i];stopPlayers();currentMedia=t.type.startsWith("video")?"video":"audio";const el=activeEl();el.src=t.url;el.volume=+$("#volume").value;$("#emptyState").classList.add("hidden");if(currentMedia==="video"){video.classList.add("video-active");$("#fullscreenBtn").classList.add("visible")}$("#currentTitle").textContent=t.name;$("#currentMeta").textContent=t.type.startsWith("video")?"Vídeo local":"Audio local";$("#mediaType").textContent=currentMedia.toUpperCase();$("#visualizerStatus").textContent="● READY";$("#visualizerContainer").classList.add("changing");setTimeout(()=>$("#visualizerContainer").classList.remove("changing"),350);renderPlaylist();if(auto)playCurrent();updateFavoriteButton()}
function playCurrent(){const el=activeEl();if(!el?.src)return;el.play().then(()=>{$("#playBtn").textContent="❚❚";$("#visualizerStatus").textContent="● PLAYING";$("#visualizerStatus").classList.add("playing");stat("plays");const t=playlist[currentIndex];history.unshift({name:t.name,url:t.url,type:t.type,time:new Date().toLocaleString("es-ES")});history=history.slice(0,50);save();renderHistory()}).catch(()=>toast("El navegador no permite iniciar automáticamente."))}
function pauseCurrent(){activeEl()?.pause();$("#playBtn").textContent="▶";$("#visualizerStatus").textContent="● PAUSED";$("#visualizerStatus").classList.remove("playing")}
$("#playBtn").onclick=()=>{const el=activeEl();if(!el?.src)return playlist.length?loadTrack(0):toast("Añade primero un archivo.");el.paused?playCurrent():pauseCurrent()};
$("#backBtn").onclick=()=>{if(activeEl().currentTime)activeEl().currentTime=Math.max(0,activeEl().currentTime-10)};
$("#forwardBtn").onclick=()=>{if(activeEl().currentTime)activeEl().currentTime=Math.min(activeEl().duration||0,activeEl().currentTime+10)};
$("#shuffleBtn").onclick=()=>{shuffle=!shuffle;$("#shuffleStatus").textContent=`ALEATORIO ${shuffle?"ON":"OFF"}`;$("#shuffleBtn").classList.toggle("active",shuffle)};
$("#repeatBtn").onclick=()=>{repeat=repeat==="off"?"one":"off";$("#repeatStatus").textContent=`REPETIR ${repeat==="one"?"ON":"OFF"}`;$("#repeatBtn").classList.toggle("active",repeat==="one")};
$("#progress").oninput=e=>{const el=activeEl();if(el.duration)el.currentTime=el.duration*(+e.target.value/100)};
["timeupdate","loadedmetadata"].forEach(ev=>[audio,video].forEach(el=>el.addEventListener(ev,()=>{if(el!==activeEl())return;$("#currentTime").textContent=formatTime(el.currentTime);$("#duration").textContent=formatTime(el.duration);$("#progress").value=el.duration?el.currentTime/el.duration*100:0})));
[audio,video].forEach(el=>el.addEventListener("ended",()=>{if(repeat==="one")return loadTrack(currentIndex);if(!playlist.length)return;let n=shuffle?Math.floor(Math.random()*playlist.length):currentIndex+1;if(n>=playlist.length)n=0;loadTrack(n)}));
$("#volume").oninput=e=>{audio.volume=video.volume=+e.target.value;$("#volumeValue").textContent=Math.round(+e.target.value*100)+"%"};
$("#muteBtn").onclick=()=>{const el=activeEl();el.muted=!el.muted;$("#muteBtn").textContent=el.muted?"🔇":"🔊"};
$("#fullscreenBtn").onclick=()=>video.requestFullscreen?.();
$("#sleepBtn").onclick=()=>$("#sleepPanel").classList.toggle("active");
$$(".sleep-panel button").forEach(b=>b.onclick=()=>{clearTimeout(sleepTimer);const m=+b.dataset.minutes;if(!m){$("#sleepStatus").textContent="Temporizador apagado";return}$("#sleepStatus").textContent=`Se detendrá en ${m} min`;sleepTimer=setTimeout(()=>{pauseCurrent();$("#sleepStatus").textContent="Temporizador finalizado"},m*60000)});
$("#fileInput").onchange=e=>{[...e.target.files].forEach(file=>{playlist.push({name:file.name,url:URL.createObjectURL(file),type:file.type,temporary:true})});renderPlaylist();if(currentIndex<0&&playlist.length)loadTrack(0);e.target.value=""};
function renderPlaylist(){const q=$("#playlistSearch").value.toLowerCase(),cat=document.querySelector(".category-btn.active")?.dataset.category||"all";let list=playlist.filter(t=>t.name.toLowerCase().includes(q));if(cat==="audio")list=list.filter(t=>t.type.startsWith("audio"));if(cat==="video")list=list.filter(t=>t.type.startsWith("video"));if(cat==="favorites")list=list.filter(t=>favorites.includes(t.name));$("#trackCount").textContent=playlist.length;$("#playlist").innerHTML=list.length?list.map(t=>{const i=playlist.indexOf(t);return`<div class="track-item ${i===currentIndex?"active":""}"><div class="track-icon">${t.type.startsWith("video")?"🎬":"🎵"}</div><div onclick="loadTrack(${i})"><div class="track-name">${escapeHtml(t.name)}</div><div class="track-meta">${t.type.split("/")[0].toUpperCase()}</div></div><div class="track-actions"><button onclick="toggleFavorite('${encodeURIComponent(t.name)}')">${favorites.includes(t.name)?"♥":"♡"}</button></div></div>`}).join(""):`<div class="empty-list">No hay archivos. Pulsa 📁 Añadir.</div>`}
function escapeHtml(x){const d=document.createElement("div");d.textContent=x;return d.innerHTML}
$("#playlistSearch").oninput=renderPlaylist;$$(".category-btn").forEach(b=>b.onclick=()=>{$$(".category-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPlaylist()});$("#clearPlaylist").onclick=()=>{playlist=[];currentIndex=-1;stopPlayers();renderPlaylist();renderLibrary()};
function toggleFavorite(encoded){const name=decodeURIComponent(encoded);favorites.includes(name)?favorites=favorites.filter(x=>x!==name):favorites.push(name);save();renderPlaylist();renderFavorites();$("#favoriteCount").textContent=`${favorites.length} canciones`;$("#favoriteSectionCount").textContent=favorites.length}
$("#favoriteBtn").onclick=()=>{if(playlist[currentIndex])toggleFavorite(encodeURIComponent(playlist[currentIndex].name));updateFavoriteButton()}
function updateFavoriteButton(){const yes=playlist[currentIndex]&&favorites.includes(playlist[currentIndex].name);$("#favoriteBtn").textContent=yes?"♥":"♡";$("#favoriteBtn").classList.toggle("active",!!yes)}
function renderLibrary(){const q=$("#librarySearch").value.toLowerCase();const list=playlist.filter(t=>t.name.toLowerCase().includes(q));$("#myMusicList").innerHTML=list.length?list.map(t=>`<div class="media-tile"><div class="tile-icon">${t.type.startsWith("video")?"🎬":"🎵"}</div><div class="tile-title">${escapeHtml(t.name)}</div><div class="tile-meta">Archivo local</div><button class="tile-btn" onclick="loadTrack(${playlist.indexOf(t)})">REPRODUCIR</button></div>`).join(""):`<div class="empty-list">Tu biblioteca aparecerá aquí al añadir archivos.</div>`}
$("#librarySearch").oninput=renderLibrary;
function renderFavorites(){const list=playlist.filter(t=>favorites.includes(t.name));$("#favoritesList").innerHTML=list.length?list.map(t=>`<div class="media-tile"><div class="tile-icon">❤️</div><div class="tile-title">${escapeHtml(t.name)}</div><div class="tile-meta">Favorito</div><button class="tile-btn" onclick="loadTrack(${playlist.indexOf(t)})">REPRODUCIR</button></div>`).join(""):`<div class="empty-list">Todavía no tienes favoritos.</div>`;$("#favoriteCount").textContent=`${favorites.length} canciones`;$("#favoriteSectionCount").textContent=favorites.length}
function renderHistory(){const list=history.slice(0,20);$("#historyList").innerHTML=list.length?list.map(h=>`<div class="media-tile"><div class="tile-icon">🕘</div><div class="tile-title">${escapeHtml(h.name)}</div><div class="tile-meta">${h.time}</div></div>`).join(""):`<div class="empty-list">No hay reproducciones todavía.</div>`;$("#historyCount").textContent=`${history.length} reproducciones`}
$("#clearHistory").onclick=()=>{history=[];save();renderHistory()};
let currentRadio=-1;
function renderRadios(){const q=$("#radioSearch").value.toLowerCase(),f=document.querySelector(".radio-filter.active")?.dataset.filter||"all";const list=radios.filter(r=>(f==="all"||r.country===f||r.tags.includes(f))&&(r.name+" "+r.country+" "+r.genre).toLowerCase().includes(q));$("#radioCount").textContent=`${list.length} emisoras`;$("#radioList").innerHTML=list.map(r=>{const i=radios.indexOf(r);return`<article class="radio-tile ${i===currentRadio?"playing":""}"><div class="tile-icon">${r.icon}</div><div class="tile-title">${r.name}</div><div class="tile-meta">${r.country} · ${r.genre}</div><button class="tile-btn" onclick="selectRadio(${i})">▶ ESCUCHAR</button></article>`}).join("")}
function selectRadio(i){currentRadio=i;const r=radios[i],a=$("#radioAudio");a.src=r.url;a.volume=+$("#radioVolume").value;a.play().then(()=>{$("#radioPlay").textContent="❚❚";$("#radioStatus").textContent="LIVE";$("#radioStatus").classList.add("live");$("#radioName").textContent=r.name;$("#radioGenre").textContent=`${r.country} · ${r.genre}`;stat("plays");renderRadios()}).catch(()=>toast("Esta emisora puede bloquear reproducción directa. Prueba otra."))}
$("#radioPlay").onclick=()=>{const a=$("#radioAudio");if(!a.src&&currentRadio<0)return toast("Selecciona una emisora.");a.paused?selectRadio(currentRadio):(a.pause(),$("#radioPlay").textContent="▶",$("#radioStatus").textContent="OFFLINE",$("#radioStatus").classList.remove("live"))};
$("#radioVolume").oninput=e=>{$("#radioAudio").volume=+e.target.value;$("#radioVolumeValue").textContent=Math.round(+e.target.value*100)+"%"};
$("#radioSearch").oninput=renderRadios;$$(".radio-filter").forEach(b=>b.onclick=()=>{$$(".radio-filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderRadios()});
const storeQty={empanada:1,player:1};
function addProduct(id,q=1){let item=cart.find(x=>x.id===id);item?item.quantity+=q:cart.push({id,quantity:q});save();renderCart();toast(`${PRODUCTS[id].name} añadido`)}
$$("[data-store-plus]").forEach(b=>b.onclick=()=>{const id=b.dataset.storePlus;storeQty[id]++;$(`#storeQty-${id}`).textContent=storeQty[id]});
$$("[data-store-minus]").forEach(b=>b.onclick=()=>{const id=b.dataset.storeMinus;storeQty[id]=Math.max(1,storeQty[id]-1);$(`#storeQty-${id}`).textContent=storeQty[id]});
$$("[data-add-product]").forEach(b=>b.onclick=()=>addProduct(b.dataset.addProduct,b.dataset.addProduct==="empanada"?storeQty.empanada:b.dataset.addProduct==="player"?storeQty.player:1));
function subtotal(){return cart.reduce((s,i)=>s+PRODUCTS[i.id].price*i.quantity,0)}
function shipping(){return cart.length&&document.querySelector('input[name="delivery"]:checked')?.value==="home"?CONFIG.shipping:0}
function total(){return subtotal()+shipping()}
function renderCart(){const list=$("#cartList");list.innerHTML=cart.length?cart.map(i=>{const p=PRODUCTS[i.id];return`<div class="cart-line"><div><b>${p.icon} ${p.name}</b><small>${i.quantity} × ${euro(p.price)}</small><div class="cart-controls"><button data-cart-minus="${i.id}">−</button><span>${i.quantity}</span><button data-cart-plus="${i.id}">+</button><button class="remove" data-cart-remove="${i.id}">Eliminar</button></div></div><strong>${euro(p.price*i.quantity)}</strong></div>`}).join(""):`<div class="empty-list">🛒 Carrito vacío. Añade productos desde Tienda.</div>`;$("#cartSubtotal").textContent=euro(subtotal());$("#cartShipping").textContent=shipping()?euro(shipping()):"0,00 €";$("#cartTotal").textContent=euro(total());$("#navCartCount").textContent=cart.reduce((s,i)=>s+i.quantity,0);updatePreview()}
document.addEventListener("click",e=>{const d=e.target.dataset;if(d.cartPlus)changeCart(d.cartPlus,1);if(d.cartMinus)changeCart(d.cartMinus,-1);if(d.cartRemove)removeCart(d.cartRemove)});
function changeCart(id,n){const x=cart.find(i=>i.id===id);if(!x)return;x.quantity+=n;if(x.quantity<=0)return removeCart(id);save();renderCart();updatePayPal()}
function removeCart(id){cart=cart.filter(i=>i.id!==id);save();renderCart();updatePayPal()}
$("#clearCart").onclick=()=>{cart=[];save();renderCart();updatePayPal()};
$$('input[name="delivery"]').forEach(x=>x.onchange=()=>{$("#addressWrap").classList.toggle("show",x.value==="home"&&x.checked);renderCart();updatePayPal()});
function orderData(){return{name:$("#customerName").value.trim(),phone:$("#customerPhone").value.trim(),address:$("#customerAddress").value.trim(),delivery:document.querySelector('input[name="delivery"]:checked').value,date:$("#orderDate").value,time:$("#orderTime").value,notes:$("#orderNotes").value.trim(),payment:document.querySelector('input[name="payment"]:checked').value}}
function orderMessage(d){const products=cart.map(i=>`🥟 *${PRODUCTS[i.id].name}:* ${i.quantity} × ${euro(PRODUCTS[i.id].price)}`).join("\n");const delivery=d.delivery==="home"?`🏠 *Entrega:* Domicilio\n📍 *Dirección:* ${d.address}\n💶 *Envío:* ${euro(CONFIG.shipping)}`:"🚉 *Entrega:* Recogida GRATIS en Estación Renfe de Azuqueca de Henares";return`⚡ *NEON PLAYER X — NUEVO PEDIDO*\n\n👤 *Nombre:* ${d.name}\n📱 *Teléfono:* ${d.phone}\n\n${products}\n\n💶 *Subtotal:* ${euro(subtotal())}\n${delivery}\n💳 *Pago:* ${d.payment==="paypal"?"PayPal":d.payment==="cash"?"Efectivo":"Confirmar por WhatsApp"}\n💰 *Total:* ${euro(total())}\n📦 *Fecha:* ${d.date}\n⏰ *Hora:* ${d.time}\n📝 *Notas:* ${d.notes||"Sin notas"}`}
function validOrder(d){if(!cart.length){toast("Añade productos al carrito.");openSection("store");return false}if(!d.name||!d.phone||!d.date||!d.time){toast("Completa los campos obligatorios.");return false}if(d.delivery==="home"&&!d.address){toast("Introduce la dirección.");return false}return true}
function sendWhatsApp(d=orderData()){if(!validOrder(d))return;const s=JSON.parse(localStorage.getItem("neonOrders")||"[]");s.unshift({...d,items:cart,total:total(),createdAt:new Date().toISOString(),status:"Nuevo"});localStorage.setItem("neonOrders",JSON.stringify(s));stat("orders");window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(orderMessage(d))}`,"_blank","noopener");toast("Pedido enviado a WhatsApp")}
$("#sendWhatsApp").onclick=()=>sendWhatsApp();
$("#orderForm").onsubmit=e=>{e.preventDefault();const d=orderData();if(!validOrder(d))return;if(d.payment==="paypal"){if(total()<=0)return;$("#paypalBox").classList.remove("hidden");loadPayPal()}else sendWhatsApp(d)};
$$('input[name="payment"]').forEach(x=>x.onchange=()=>{if(x.checked&&x.value==="paypal"){if(!validOrder(orderData()))return;$("#paypalBox").classList.remove("hidden");loadPayPal()}else $("#paypalBox").classList.add("hidden")});
function updatePreview(){const d=orderDataSafe();$("#orderPreview").textContent=cart.length?orderMessage(d):"👤 Nombre: ...\n🥟 Cantidad: ...\n💶 Total: 0,00 €\n📦 Entrega: ...\n📅 Fecha: ..."}
function orderDataSafe(){return{name:$("#customerName")?.value.trim()||"...",phone:$("#customerPhone")?.value.trim()||"...",address:$("#customerAddress")?.value.trim()||"...",delivery:document.querySelector('input[name="delivery"]:checked')?.value||"pickup",date:$("#orderDate")?.value||"...",time:$("#orderTime")?.value||"...",notes:$("#orderNotes")?.value.trim()||"",payment:document.querySelector('input[name="payment"]:checked')?.value||"whatsapp"}}
["customerName","customerPhone","customerAddress","orderDate","orderTime","orderNotes"].forEach(id=>$("#"+id).addEventListener("input",updatePreview));
let paypalLoaded=false,paypalRendered=false;
function loadPayPal(){if(paypalRendered){updatePayPal();return}if(window.paypal){renderPayPal();return}if(paypalLoaded)return;paypalLoaded=true;const s=document.createElement("script");s.src=`https://www.paypal.com/sdk/js?client-id=${CONFIG.paypalClientId}&currency=EUR&intent=capture&components=buttons`;s.onload=renderPayPal;s.onerror=()=>toast("No se pudo cargar PayPal.");document.head.appendChild(s)}
function renderPayPal(){if(!window.paypal)return;const c=$("#paypal-button-container");c.innerHTML="";window.paypal.Buttons({style:{layout:"vertical",shape:"rect",height:42,label:"paypal"},createOrder:(data,actions)=>actions.order.create({purchase_units:[{description:"Pedido NEON PLAYER X",amount:{currency_code:"EUR",value:total().toFixed(2)}}]}),onApprove:(data,actions)=>actions.order.capture().then(details=>{const d=orderData();const s=JSON.parse(localStorage.getItem("neonOrders")||"[]");s.unshift({...d,items:cart,total:total(),paypalOrderId:data.orderID,paymentStatus:"COMPLETADO",createdAt:new Date().toISOString(),status:"Pagado"});localStorage.setItem("neonOrders",JSON.stringify(s));stat("orders");window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(orderMessage({...d,payment:"paypal"})+"\n\n✅ *Pago PayPal completado.*\n🧾 *ID PayPal:* "+data.orderID)}`,"_blank","noopener");toast("Pago completado correctamente.")}),onError:()=>toast("PayPal ha informado de un error.")}).render(c);paypalRendered=true}
function updatePayPal(){if(paypalRendered){paypalRendered=false;renderPayPal()}}
$("#googleSearch").onsubmit=e=>{e.preventDefault();const q=$("#googleInput").value.trim();if(q)window.open("https://www.google.com/search?q="+encodeURIComponent(q),"_blank","noopener")};
$("#shareBtn").onclick=async()=>{try{if(navigator.share){await navigator.share({title:"Neon Player X",text:"Música, vídeo, radio y tienda NEON PLAYER X",url:location.href)}else await navigator.clipboard.writeText(location.href);stat("shares");toast("Enlace compartido")}catch{}};
$("#themeBtn").onclick=()=>{themeIndex=(themeIndex+1)%themes.length;localStorage.setItem("neonThemeIndex",themeIndex);document.body.dataset.theme=themes[themeIndex]==="purple"?"":themes[themeIndex];toast("Tema: "+themes[themeIndex])};
function initPWA(){let deferred=null;addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$("#installBtn").hidden=true};addEventListener("appinstalled",()=>{stat("installs");$("#installBtn").hidden=true})}
function init(){document.body.dataset.theme=themes[themeIndex]==="purple"?"":themes[themeIndex];$("#year").textContent=new Date().getFullYear();setInterval(updateClock,1000);updateClock();const today=new Date().toISOString().split("T")[0];$("#orderDate").min=today;$("#orderDate").value=today;$("#orderTime").value=new Date().toTimeString().slice(0,5);if(!sessionStorage.getItem("neonVisit")){sessionStorage.setItem("neonVisit","1");stat("visits")}activity();renderPlaylist();renderLibrary();renderFavorites();renderHistory();renderRadios();renderCart();updatePreview();initPWA();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});if(localStorage.getItem("neonStats"))activity()}
init();