const $ = (id) => document.getElementById(id);
const dropZone = $('dropZone') || $('dropzone'); const fileInput = $('fileInput') || $('file-input'); const player = $('player'); const mediaFrame = $('mediaFrame'); const fileType = $('fileType'); const fileName = $('fileName'); const fileMeta = $('fileMeta'); const playButton = $('playButton'); const progress = $('progress'); const currentTime = $('currentTime'); const duration = $('duration'); const downloadButton = $('downloadButton');
const radioAudio = $('radioAudio'); const radioSelect = $('radioSelect'); const stationGrid = $('stationGrid'); const newsList = $('newsList'); let media; let objectUrl; let audioContext; let bassFilter; let trebleFilter; let newsItems = []; let newsIndex = 0;
let activeNewsFeed = 'tech';
const stations = [
  { name: 'Los 40 España', genre: 'Éxitos / España', url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40.mp3' },
  { name: 'Los 40 Urban', genre: 'Urbano / España', url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/LOS40URBAN.mp3' },
  { name: 'Hit FM', genre: 'Dance / Europa', url: 'https://hitfm.ondemand.stream.radiojar.com/8s5u5tpdtwzuv' },
  { name: 'Onda Cero', genre: 'Actualidad / España', url: 'https://atres-live-ondacero.flumotion.com/ondacero/stream.mp3' },
  { name: 'Radio Marca', genre: 'Deportes / España', url: 'https://radiomarca-cope.flumotion.com/radiomarca/radiomarca.mp3' },
  { name: 'Cadena SER', genre: 'Actualidad / España', url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3' }
];
const feeds = { tech: 'https://feeds.bbci.co.uk/news/technology/rss.xml', science: 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml', crypto: 'https://www.coindesk.com/arc/outboundfeeds/rss/', latam: 'https://feeds.bbci.co.uk/mundo/rss.xml' };
function formatTime(seconds) { if (!Number.isFinite(seconds)) return '00:00'; return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`; }
function formatBytes(bytes) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function loadFile(file) { if (!file || (!file.type.startsWith('audio/') && !file.type.startsWith('video/') && !/\.(mp3|wav|mp4|webm)$/i.test(file.name))) return; if (objectUrl) URL.revokeObjectURL(objectUrl); objectUrl = URL.createObjectURL(file); const isVideo = file.type.startsWith('video/') || /\.(mp4|webm)$/i.test(file.name); mediaFrame.innerHTML = `<${isVideo ? 'video' : 'audio'} controls preload="metadata"></${isVideo ? 'video' : 'audio'}>`; media = mediaFrame.querySelector('audio, video'); media.src = objectUrl; media.addEventListener('loadedmetadata', () => { duration.textContent = formatTime(media.duration); }); media.addEventListener('timeupdate', updateProgress); media.addEventListener('play', () => { playButton.textContent = '❚❚'; }); media.addEventListener('pause', () => { playButton.textContent = '▶'; }); fileType.textContent = isVideo ? 'VÍDEO' : 'AUDIO'; fileName.textContent = file.name; fileMeta.textContent = `${isVideo ? 'Vídeo' : 'Audio'} local · ${formatBytes(file.size)}`; downloadButton.href = objectUrl; downloadButton.download = file.name; player.hidden = false; dropZone.hidden = true; media.play().catch(() => {}); }
function updateProgress() { if (!media) return; progress.value = media.duration ? (media.currentTime / media.duration) * 100 : 0; currentTime.textContent = formatTime(media.currentTime); }
function openPicker() { fileInput.click(); }
dropZone.addEventListener('click', openPicker); dropZone.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openPicker(); } }); fileInput.addEventListener('change', (event) => loadFile(event.target.files[0]));
['dragenter', 'dragover'].forEach((name) => dropZone.addEventListener(name, (event) => { event.preventDefault(); dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach((name) => dropZone.addEventListener(name, (event) => { event.preventDefault(); dropZone.classList.remove('dragging'); })); dropZone.addEventListener('drop', (event) => loadFile(event.dataTransfer.files[0]));
playButton.addEventListener('click', () => { if (media?.paused) media.play(); else media?.pause(); }); progress.addEventListener('input', () => { if (media?.duration) media.currentTime = (progress.value / 100) * media.duration; });
function togglePanel(button, panel) { const open = button.getAttribute('aria-expanded') === 'true'; document.querySelectorAll('.control-button').forEach((item) => item.setAttribute('aria-expanded', 'false')); document.querySelectorAll('.control-panel').forEach((item) => { item.hidden = true; }); button.setAttribute('aria-expanded', String(!open)); panel.hidden = open; }
$('volumeToggle').addEventListener('click', () => togglePanel($('volumeToggle'), $('volumePanel'))); $('speedToggle').addEventListener('click', () => togglePanel($('speedToggle'), $('speedPanel'))); $('eqToggle').addEventListener('click', () => togglePanel($('eqToggle'), $('eqPanel')));
$('volumeControl').addEventListener('input', (event) => { const value = Number(event.target.value); if (media) media.volume = value; $('volumeValue').textContent = `${Math.round(value * 100)}%`; $('volumeOutput').textContent = `${Math.round(value * 100)}%`; });
document.querySelectorAll('[data-speed]').forEach((button) => button.addEventListener('click', () => { if (media) media.playbackRate = Number(button.dataset.speed); $('speedToggle').firstChild.textContent = `${button.dataset.speed}×`; document.querySelectorAll('[data-speed]').forEach((item) => item.classList.toggle('active', item === button)); }));
function ensureAudioGraph() { if (audioContext || !media || media.tagName !== 'AUDIO') return; const AudioContextClass = window.AudioContext || window.webkitAudioContext; if (!AudioContextClass) return; audioContext = new AudioContextClass(); const source = audioContext.createMediaElementSource(media); bassFilter = audioContext.createBiquadFilter(); bassFilter.type = 'lowshelf'; bassFilter.frequency.value = 180; trebleFilter = audioContext.createBiquadFilter(); trebleFilter.type = 'highshelf'; trebleFilter.frequency.value = 3500; source.connect(bassFilter).connect(trebleFilter).connect(audioContext.destination); }
$('bassControl').addEventListener('input', (event) => { ensureAudioGraph(); if (bassFilter) bassFilter.gain.value = Number(event.target.value); $('bassOutput').textContent = `${event.target.value} dB`; }); $('trebleControl').addEventListener('input', (event) => { ensureAudioGraph(); if (trebleFilter) trebleFilter.gain.value = Number(event.target.value); $('trebleOutput').textContent = `${event.target.value} dB`; });
document.addEventListener('click', (event) => { if (!event.target.closest('.control-menu')) { document.querySelectorAll('.control-button').forEach((item) => item.setAttribute('aria-expanded', 'false')); document.querySelectorAll('.control-panel').forEach((item) => { item.hidden = true; }); } });
function renderStations() { radioSelect.innerHTML = '<option value="">Selecciona una emisora</option>' + stations.map((station, index) => `<option value="${index}">${station.name} // ${station.genre}</option>`).join(''); stationGrid.innerHTML = stations.map((station, index) => `<article class="station-card"><span class="station-live">LIVE // ESPAÑA</span><strong>${station.name}</strong><small>${station.genre}</small><button type="button" data-station="${index}">▶ SINTONIZAR</button></article>`).join(''); stationGrid.querySelectorAll('[data-station]').forEach((button) => button.addEventListener('click', () => tuneRadio(Number(button.dataset.station)))); }
function tuneRadio(index) { const station = stations[index]; if (!station) return; radioSelect.value = String(index); radioAudio.src = station.url; radioAudio.play().catch(() => {}); }
$('radioPlay').addEventListener('click', () => { if (radioSelect.value === '') return; tuneRadio(Number(radioSelect.value)); }); $('radioStop').addEventListener('click', () => radioAudio.pause()); radioSelect.addEventListener('change', () => { if (radioSelect.value !== '') tuneRadio(Number(radioSelect.value)); });
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])); }
function renderNewsCarousel() { if (!newsItems.length) { newsList.innerHTML = '<p class="news-status">No hay titulares disponibles.</p>'; return; } const item = newsItems[newsIndex]; newsList.innerHTML = `<a class="news-item" href="${escapeHtml(item.link)}" target="_blank" rel="noopener"><time>${escapeHtml(item.date)} · ${escapeHtml(item.source || 'Actualidad')}</time><strong>${escapeHtml(item.title)}</strong></a>`; }
async function loadNews(feed = activeNewsFeed, forceRefresh = false) { activeNewsFeed = feed; newsList.innerHTML = '<p class="news-status">ACTUALIZANDO TITULARES...</p>'; $('syncStatus').textContent = 'CONECTANDO CON FUENTES WEB...'; try { const refresh = forceRefresh ? '&refresh=1' : ''; const response = await fetch(`/api/news?feed=${encodeURIComponent(feed)}${refresh}`); if (!response.ok) throw new Error('feed'); newsItems = await response.json(); newsIndex = 0; renderNewsCarousel(); $('syncStatus').textContent = `WEB SINCRONIZADA · ${new Date().toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' })}`; } catch { newsItems = []; newsList.innerHTML = '<p class="news-status">No se pudo conectar al servicio de noticias. Inicia el servidor para sincronizar datos web.</p>'; $('syncStatus').textContent = 'SIN CONEXIÓN WEB'; } }
function moveNews(step) { if (!newsItems.length) return; newsIndex = (newsIndex + step + newsItems.length) % newsItems.length; renderNewsCarousel(); }
document.querySelectorAll('.news-filter').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.news-filter').forEach((item) => item.classList.toggle('active', item === button)); loadNews(button.dataset.feed); })); $('refreshNews').addEventListener('click', () => loadNews(activeNewsFeed, true)); $('newsPrevious').addEventListener('click', () => moveNews(-1)); $('newsNext').addEventListener('click', () => moveNews(1));
function setView(view) { const views = { music: $('musicView'), radio: $('radioView'), news: $('newsView') }; Object.entries(views).forEach(([name, element]) => { element.hidden = name !== view; }); document.querySelectorAll('.tab').forEach((tab) => tab.classList.toggle('active', tab.id === `${view}Tab`)); if (view === 'news' && newsList.querySelector('.news-status')) loadNews(); }
$('musicTab').addEventListener('click', () => setView('music')); $('radioTab').addEventListener('click', () => setView('radio')); $('newsTab').addEventListener('click', () => setView('news')); $('vrButton').addEventListener('click', () => { $('vrOverlay').hidden = false; }); $('vrClose').addEventListener('click', () => { $('vrOverlay').hidden = true; }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') $('vrOverlay').hidden = true; });
function updateClock() { const now = new Date(); const hours = String(now.getHours()).padStart(2, '0'); const minutes = String(now.getMinutes()).padStart(2, '0'); const seconds = String(now.getSeconds()).padStart(2, '0'); const clock = $('onlineClock') || $('clock'); if (clock) clock.textContent = `${hours}:${minutes}:${seconds}`; }
renderStations(); updateClock(); setInterval(updateClock, 1000); setInterval(() => { if (!$('newsView').hidden) loadNews(activeNewsFeed, true); }, 24 * 60 * 60 * 1000); media = null;
