-- NEON PLAYER X — ESTADÍSTICAS GLOBALES
-- Ejecuta TODO este archivo en Supabase SQL Editor.

create table if not exists public.neon_stats (
    id smallint primary key,
    total_visits bigint not null default 0,
    unique_visitors bigint not null default 0,
    total_sessions bigint not null default 0,
    total_plays bigint not null default 0,
    total_radio_plays bigint not null default 0,
    total_installs bigint not null default 0,
    total_shares bigint not null default 0,
    updated_at timestamptz not null default now()
);

insert into public.neon_stats(id)
values(1)
on conflict(id) do nothing;

create table if not exists public.neon_visitors (
    visitor_id uuid primary key,
    first_seen timestamptz not null default now(),
    last_seen timestamptz not null default now()
);

create table if not exists public.neon_events (
    id bigint generated by default as identity primary key,
    event_type text not null,
    visitor_id uuid,
    session_id text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.neon_stats enable row level security;
alter table public.neon_visitors enable row level security;
alter table public.neon_events enable row level security;

revoke all on table public.neon_stats from anon, authenticated;
revoke all on table public.neon_visitors from anon, authenticated;
revoke all on table public.neon_events from anon, authenticated;

create or replace function public.neon_get_stats()
returns json
language sql
security definer
set search_path = public
as $$
    select json_build_object(
        'totalVisits',total_visits,
        'uniqueVisitors',unique_visitors,
        'totalSessions',total_sessions,
        'totalPlays',total_plays,
        'totalRadioPlays',total_radio_plays,
        'totalInstalls',total_installs,
        'totalShares',total_shares
    )
    from public.neon_stats
    where id=1;
$$;

create or replace function public.neon_register_event(
    p_event_type text,
    p_visitor_id uuid,
    p_session_id text,
    p_metadata jsonb default '{}'::jsonb
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    is_new_visitor boolean := false;
begin

    if p_event_type is null
       or p_event_type not in(
           'visit',
           'play',
           'radio_play',
           'install',
           'share'
       )
    then
        raise exception 'Evento no permitido';
    end if;

    if p_visitor_id is not null then

        begin

            insert into public.neon_visitors(
                visitor_id
            )
            values(
                p_visitor_id
            );

            is_new_visitor := true;

        exception
            when unique_violation then

                update public.neon_visitors
                set last_seen=now()
                where visitor_id=p_visitor_id;
        end;

    end if;

    if p_event_type='visit' then

        update public.neon_stats
        set
            total_visits=total_visits+1,
            total_sessions=total_sessions+1,
            unique_visitors=
                unique_visitors+
                case
                    when is_new_visitor then 1
                    else 0
                end,
            updated_at=now()
        where id=1;

    elsif p_event_type='play' then

        update public.neon_stats
        set
            total_plays=total_plays+1,
            updated_at=now()
        where id=1;

    elsif p_event_type='radio_play' then

        update public.neon_stats
        set
            total_plays=total_plays+1,
            total_radio_plays=
                total_radio_plays+1,
            updated_at=now()
        where id=1;

    elsif p_event_type='install' then

        update public.neon_stats
        set
            total_installs=total_installs+1,
            updated_at=now()
        where id=1;

    elsif p_event_type='share' then

        update public.neon_stats
        set
            total_shares=total_shares+1,
            updated_at=now()
        where id=1;

    end if;

    insert into public.neon_events(
        event_type,
        visitor_id,
        session_id,
        metadata
    )
    values(
        p_event_type,
        p_visitor_id,
        left(coalesce(p_session_id,''),120),
        coalesce(p_metadata,'{}'::jsonb)
    );

    return public.neon_get_stats();

end;
$$;

revoke all on function public.neon_get_stats()
from public;

revoke all on function public.neon_register_event(
    text,uuid,text,jsonb
)
from public;

grant execute on function public.neon_get_stats()
to anon,authenticated;

grant execute on function public.neon_register_event(
    text,uuid,text,jsonb
)
to anon,authenticated;
